INSERT INTO _UIX (ID,PRIORITY,CODE,NAME,TYPE,LEVEL,ATTRIBUTE,PARENT,APPLICATION,LAYOUT,STEPPER,[SCHEMA])
VALUES (601,601,'ADMINPORTAL','Admin Portal','APP', 6, '{"icon":"ThePlace"}','[401]',NULL,'[1]',NULL,NULL),
(602,602,'VENDORPORTAL','Vendor Portal','APP', 6, '{"icon":"ThePlace"}','[401]',NULL,'[1]',NULL,NULL),
(603,603,'ACCOUNTING','Accounting','APP', 6, '{"icon":"Accounting"}','[401]',NULL,'[1]',NULL,NULL)