INSERT INTO _UIX (ID,PRIORITY,CODE,NAME,TYPE,LEVEL,ATTRIBUTE,PARENT,APPLICATION,LAYOUT,STEPPER,[SCHEMA])
VALUES 	(801,801,'DSHSCH','DashboardSearch','SEARCH TEXT', 6, '[421]',NULL, '[601]',NULL,NULL,NULL),
	(802,802,'MODSCH','ModuleSearch','SEARCH TEXT', 6, '[422]',NULL, '[601]',NULL,NULL,NULL)