DELETE FROM _UIX WHERE ID > 200 AND ID < 401
SELECT * FROM _UIX WHERE ID > 200 AND ID < 401

INSERT INTO _UIX (ID,PRIORITY,CODE,TYPE,NAME,LEVEL,ATTRIBUTE,PARENT,APPLICATION,LAYOUT)
VALUES  
(201,2,'LEFTAREA','LeftArea1','Left Area', 2, NULL,'[1]',NULL,NULL), (202,2,'LEFTAREA','LeftArea2','Left Area', 2, NULL,NULL,NULL,NULL),  (203,2,'LEFTAREA','LeftArea3','Left Area', 2, NULL,NULL,NULL,NULL),
(204,2,'LEFTAREA','LeftArea4','Left Area', 2, NULL,NULL,NULL,NULL), (205,2,'LEFTAREA','LeftArea5','Left Area', 2, NULL,NULL,NULL,NULL),(206,2,'LEFTAREA','LeftArea6','Left Area', 2, NULL,NULL,NULL,NULL),
(207,2,'LEFTAREA','LeftArea7','Left Area', 2, NULL,NULL,NULL,NULL),(208,2,'LEFTAREA','LeftArea8','Left Area', 2, NULL,NULL,NULL,NULL),(209,2,'LEFTAREA','LeftArea9','Left Area', 2, NULL,NULL,NULL,NULL),
(210,2,'LEFTAREA','LeftArea10','Left Area', 2, NULL,NULL,NULL,NULL),(211,2,'LEFTAREA','LeftArea11','Left Area', 2, NULL,NULL,NULL,NULL),(212,2,'LEFTAREA','LeftArea12','Left Area', 2, NULL,NULL,NULL,NULL),
(213,2,'LEFTAREA','LeftArea13','Left Area', 2, NULL,NULL,NULL,NULL),(214,2,'LEFTAREA','LeftArea14','Left Area', 2, NULL,NULL,NULL,NULL),(215,2,'LEFTAREA','LeftArea15','Left Area', 2, NULL,NULL,NULL,NULL),
(216,2,'LEFTAREA','LeftArea16','Left Area', 2, NULL,NULL,NULL,NULL),(217,2,'LEFTAREA','LeftArea17','Left Area', 2, NULL,NULL,NULL,NULL),(218,2,'LEFTAREA','LeftArea18','Left Area', 2, NULL,NULL,NULL,NULL),
(219,2,'LEFTAREA','LeftArea19','Left Area', 2, NULL,NULL,NULL,NULL),(220,2,'LEFTAREA','LeftArea20','Left Area', 2, NULL,NULL,NULL,NULL),(221,2,'LEFTAREA','LeftArea21','Left Area', 2, NULL,NULL,NULL,NULL),
(222,2,'LEFTAREA','LeftArea22','Left Area', 2, NULL,NULL,NULL,NULL),(223,2,'LEFTAREA','LeftArea23','Left Area', 2, NULL,NULL,NULL,NULL),(224,2,'LEFTAREA','LeftArea24','Left Area', 2, NULL,NULL,NULL,NULL),
(225,2,'LEFTAREA','LeftArea25','Left Area', 2, NULL,NULL,NULL,NULL)

