DELETE FROM _UIX WHERE ID > 200 AND ID < 401
SELECT * FROM _UIX WHERE ID > 200 AND ID < 401

INSERT INTO _UIX (ID,PRIORITY,CODE,TYPE,NAME,LEVEL,ATTRIBUTE,PARENT,APPLICATION,LAYOUT)
VALUES  
(1,2,'DESKTOPLAYOUT','DesktopLayout1','Desktop Layout', 2, NULL,'[1]',NULL,NULL)

